site_name: Cameron's Pages
site_author: Cameron Kleiman
site_description: A documentation website for Cameron Kleiman
copyright: Cameron Kleiman
repo_url: https://github.com/camtheman256/pages
edit_uri: edit/main/docs

site_url: https://pages.camk.co/


theme:
  name: material
  icon:
    logo: material/book
  features:
    - navigation.tabs
    - navigation.footer
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition

extra:
  analytics:
    provider: google
    property: G-0773QM221F

plugins:
  - social