[tool.poetry]
name = "pages"
version = "0.1.0"
description = "Cameron's Pages"
authors = ["Cameron Kleiman <camtheman256@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mkdocs-material = "^9.4.3"
Pillow = "^10.0.1"
CairoSVG = "^2.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
